In [2]:
import pandas as pd 
def romaneios_executados(caminho1, caminho2):
    #define os dataframes baseado nos dados fornecidos
    romaneio_executado = pd.read_excel(caminho1)
    romaneio_emitido = pd.read_excel(caminho2)
    #exclui a primeira linha do dataframe
    romaneio_emitido.drop([0], axis= 0 , inplace=True)
    #cria um novo dataframe baseado na coluna, romaneio do 1 dataframe, FRT.AGREGADO APURADO do segundo dataframe
    romaneio_final = pd.merge(romaneio_executado[["ROMANEIO"]], 
                          romaneio_emitido[["ROMANEIO", "FRT.AGREGADO APURADO"]],
                          on="ROMANEIO", 
                          how="left")
    #renomeia a coluna para apurado
    romaneio_final.rename({"FRT.AGREGADO APURADO":"APURADO"}, axis=1, inplace=True)
    
    #cria um novo dataframe e utiliza a função merge, para juntar os dataframes com base na coluna romaneio
    romaneio_executado = pd.merge(romaneio_executado, romaneio_final, on="ROMANEIO", how="left")
    
    #muda o tipo de dado da coluna romaneio para string e adiciona um campo de 6 valores padrões para os valores nas celulas
    romaneio_executado['ROMANEIO'] = romaneio_executado['ROMANEIO'].astype(str)
    romaneio_executado['ROMANEIO'] = romaneio_executado['ROMANEIO'].str.zfill(6)
    
    #salva o arquivo
    romaneio_executado.to_excel("Romaneios_Março_BHZ_teste.xlsx")
    #faz o retorno do dataframe finalizado 
    return romaneio_executado
    
#variaveis utilizadas para especificar os caminhos a função   
caminho1 = "ROMANEIO_EXECUTADOS_SPO.XLSX"
caminho2 = "ROMANEIO_EMITIDOS_SPO.XLSX"
#executando a função e joga o resultado(dataframe) em uma nova variavel
romaneio_executado = romaneios_executados(caminho1, caminho2)
#exibe o dataframe finalizado
display(romaneio_executado)

,FIL_ROMANEIO,ROMANEIO,DT_EMISSAO,DT_BAIXA,CAVALO,REBOQUE_1,REBOQUE_2,REC_FILIAL,REC_NUMERO,REC_EMISSAO,...,TIPO_CARREGAMENTO,ID_KRONA,CIOT_URL,PEDG_TIPO,PEDG_CATEGORIA,PBR_TERCEIROS,CHP_TERCEIROS,MDFE_XMLCANCELAMENTO,CIOT_SERVICO,APURADO
0,SPO,2739.0,2024-03-01 08:31:00,2024-03-01 08:31:00,MYO-9718,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,250.0
1,SPO,2740.0,2024-03-04 08:06:00,2024-03-04 08:06:00,DSD-6A25,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,320.0
2,SPO,2741.0,2024-03-04 08:13:00,2024-03-04 08:13:00,MXO-8370,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,200.0
3,SPO,2742.0,2024-03-04 15:00:00,2024-03-04 15:00:00,FBQ-0Q11,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,900.0
4,SPO,2744.0,2024-03-04 16:20:00,2024-03-04 16:20:00,MXO-8370,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SPO,2837.0,2024-03-28 08:12:00,2024-03-28 08:12:00,MYO-9718,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,NaN
95,SPO,2838.0,2024-03-28 09:19:00,2024-03-28 09:19:00,NGO-4G96,NaN,NaN,SPO,598.0,2024-04-02,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,NaN
96,SPO,2839.0,2024-03-28 11:12:00,2024-03-28 11:12:00,KKP-3721,NaN,NaN,SPO,593.0,2024-03-28,...,NaN,NaN,NaN,3.0,2.0,0,0,NaN,NaN,NaN
97,SPO,2841.0,2024-03-28 18:14:00,2024-03-28 18:14:00,EZG-2D15,NaN,NaN,SPO,597.0,2024-04-02,...,NaN,NaN,NaN,3.0,4.0,0,0,NaN,NaN,NaN
98,98,000nan,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN